[build]
  publish = "public"
  functions = "netlify/functions" # กำหนดโฟลเดอร์ functions output
  command = "npm install && npm run build:functions" # เปลี่ยน Build Command ให้เรียก script ใน package.json

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]
  # directory = "api" # ไม่ต้องระบุตรงนี้แล้ว เพราะเราจะให้ build:functions จัดการ
  # included_files = ["api/cases.cjs", "package.json", "node_modules/**"] # ลบออกเพื่อลดความซับซ้อน
