[build]
  publish = "public"
  functions = "api"
  command = "npm install" # This will install dependencies for both frontend (if any) and functions

[functions]
  node_bundler = "esbuild" # Use esbuild for faster and more efficient bundling
  external_node_modules = ["firebase-admin"] # Explicitly tell Netlify to bundle firebase-admin
  node_version = "20" # Specify Node.js version for functions
