[build]
  publish = "public"
  functions = "api"
  command = "npm install" # This will install dependencies for both frontend (if any) and functions

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]
  directory = "api"
  included_files = ["api/cases.cjs", "package.json", "node_modules/**"]
